Create Use-Case Interactors = Presenters with Backend for join/create/list games
FiveTotallySpies/Spydle pull request #52
Opened 2024-11-19 03:23 UTC by klokailo

2024-11-22 23:42 UTC, xinlei55555 requested changes
A few elements of uncertainty

2024-11-22 23:42 UTC, xinlei55555 commented on frontend/src/main/java/dev/totallyspies/spydle/frontend/interface_adapters/list_rooms/ListRoomsViewModel.java
I am not sure if we want an array here, as the size couldn't be changed afterwards, and I am guessing we want the number of rooms to not be fixed

2024-11-22 23:42 UTC, xinlei55555 commented on frontend/src/main/java/dev/totallyspies/spydle/frontend/interface_adapters/welcome/WelcomeViewController.java
You mentioned in the past that we should use the constructor instead, and declare the @Autowired through the constructor, should we do this, or is declaring each attribute separately in the class also okay?

2024-11-22 23:42 UTC, xinlei55555 commented on frontend/src/main/java/dev/totallyspies/spydle/frontend/interface_adapters/welcome/WelcomeViewModel.java
Good idea for the default value, or else it just printed "Enter Your Name".

2024-11-23 02:29 UTC, klokailo commented on frontend/src/main/java/dev/totallyspies/spydle/frontend/interface_adapters/list_rooms/ListRoomsViewModel.java
What is stored in the view model is just the actually array of lines that we write in the text field. This is following clean architecture.
In the case that more rooms are created, we simply can simply poll the `/list-games` endpoint and create a new array using the `List<String>` of rooms it returns.

2024-11-23 02:30 UTC, klokailo commented on frontend/src/main/java/dev/totallyspies/spydle/frontend/interface_adapters/welcome/WelcomeViewController.java
Yes, I can change these to use constructor dependency injection.

2024-11-24 19:11 UTC, xinlei55555 commented on frontend/src/main/java/dev/totallyspies/spydle/frontend/interface_adapters/list_rooms/ListRoomsViewModel.java
Good to know :+1:

2024-11-24 19:12 UTC, xinlei55555 approved these changes

2024-11-24 19:12 UTC, merged